// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Domain.Model.Todolist.Todo_List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Created_By")
                        .HasColumnType("TEXT");

                    b.Property<string>("List_Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todolists");
                });

            modelBuilder.Entity("Domain.Model.Todolist.Todo_Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Created_By")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Due_Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("List_ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Task_Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Task_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todolist_Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
