/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Todo_Task {
  id?: string;
  list_ID: string;
  task_Name: string;
  task_Description?: string;
  due_Date: string;
  created_By?: string;
  date_Created?: unknown;
  date_Modified?: unknown;
}
