/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Todo_List {
  id?: string;
  list_Title: string;
  created_By?: string;
  date_Created?: unknown;
  date_Modified?: unknown;
}
