/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface User {
  id?: string;
  username: string;
  password: string;
  userInformation?: UserInformation;
  created_By?: string;
  date_Created: unknown;
  date_Modified?: unknown;
}
export interface UserInformation {
  id?: string;
  firstName?: string;
  middleName?: string;
  lastName?: string;
  email?: string;
  phoneNumber?: string;
  image?: string;
}
